### ISSUE TITLE
Convert to exe

### ISSUE THREAD

**Issue by Hastez** [backslash/AngstStealer#1343]
How should we go about converting this file to an executable, are there any specific steps we may need to take?

**Comment by backslash** [comment]
`6. Run one of the following commands listed below, it is worth noting that pyarmor will sometimes corrupt the executable so if you plan on using the pyarmor command you should test it locally to make sure it works.
PYINSTALLER: pyinstaller --onefile --hidden-import=pkg_resources.py2_warn angst.py
PYARMOR: pyarmor pack -e " --onefile --hidden-import=pkg_resources.py2_warn" angst.py`
i mentioned this in the readme please check that for reference
